package com.whippahh.progressscape;

/**
 * Combat Achievement tasks in their in-game order (0-indexed).
 * Completion is stored as individual bits within VarPlayers starting at 2616.
 * Task N: varp = 2616 + (N / 32), bit = N % 32
 */
public enum CombatAchievement
{
    NOXIOUS_FOE("Noxious Foe"),
    BARROWS_NOVICE("Barrows Novice"),
    DEFENCE_WHAT_DEFENCE("Defence? What Defence?"),
    BIG_BLACK_AND_FIERY("Big, Black and Fiery"),
    THE_DEMONIC_PUNCHING_BAG("The Demonic Punching Bag"),
    BRUTUS_NOVICE("Brutus Novice"),
    PROTECTION_FROM_MOSS("Protection from Moss"),
    BRYOPHYTA_NOVICE("Bryophyta Novice"),
    A_SLOW_DEATH("A Slow Death"),
    PREPARATION_IS_KEY("Preparation Is Key"),
    FIGHTING_AS_INTENDED_II("Fighting as Intended II"),
    DERANGED_ARCHAEOLOGIST_NOVICE("Deranged Archaeologist Novice"),
    THE_WALKING_VOLCANO("The Walking Volcano"),
    GIANT_MOLE_NOVICE("Giant Mole Novice"),
    A_GREATER_FOE("A Greater Foe"),
    NOT_SO_GREAT_AFTER_ALL("Not So Great After All"),
    A_DEMON("A Demon\"),
    KING_BLACK_DRAGON_NOVICE("King Black Dragon Novice"),
    SHAYZIEN_PROTECTOR("Shayzien Protector"),
    A_SCALEY_ENCOUNTER("A Scaley Encounter"),
    INTO_THE_DEN_OF_GIANTS("Into the Den of Giants"),
    FIGHTING_AS_INTENDED("Fighting as Intended"),
    SLEEPING_GIANT("Sleeping Giant"),
    OBOR_NOVICE("Obor Novice"),
    ONE_BY_ONE("One by one"),
    ELEMENTAL_COMPANY("Elemental Company"),
    LET_THEM_FIGHT("Let them fight"),
    SARACHNIS_NOVICE("Sarachnis Novice"),
    SCURRIUS_NOVICE("Scurrius Novice"),
    SIT_RAT("Sit Rat"),
    SHELLBANE_ADEPT("Shellbane Adept"),
    DRY_CLEANING("Dry Cleaning"),
    CALM_BEFORE_THE_STORM("Calm Before the Storm"),
    MASTER_OF_BUCKETS("Master of Buckets"),
    TEMPOROSS_NOVICE("Tempoross Novice"),
    FIRE_IN_THE_HOLE("Fire in the Hole!"),
    COSY("Cosy"),
    HANDYMAN("Handyman"),
    WINTERTODT_NOVICE("Wintertodt Novice"),
    MUMMY("Mummy!"),
    A_SLITHERY_ENCOUNTER("A Slithery Encounter"),
    AMOXLIATL_CHAMPION("Amoxliatl Champion"),
    TEMOTLI_TRIUMPH("Temotli Triumph"),
    CAN("Can\"),
    PRAY_FOR_SUCCESS("Pray for Success"),
    BARROWS_CHAMPION("Barrows Champion"),
    BRUTAL_BIG_BLACK_AND_FIREY("Brutal, Big, Black and Firey"),
    BRUTUS_CHAMPION("Brutus Champion"),
    BEEF_VS_BEEF("Beef vs Beef"),
    QUICK_CUTTER("Quick Cutter"),
    BRYOPHYTA_CHAMPION("Bryophyta Champion"),
    CHAOS_FANATIC_CHAMPION("Chaos Fanatic Champion"),
    SORRY_WHAT_WAS_THAT("Sorry, What Was That?"),
    I("I\"),
    MAGE_OF_THE_RUINS("Mage of the Ruins"),
    CRAZY_ARCHAEOLOGIST_CHAMPION("Crazy Archaeologist Champion"),
    DAGANNOTH_PRIME_CHAMPION("Dagannoth Prime Champion"),
    A_FROZEN_KING("A Frozen King"),
    DAGANNOTH_REX_CHAMPION("Dagannoth Rex Champion"),
    DAGANNOTH_SUPREME_CHAMPION("Dagannoth Supreme Champion"),
    DERANGED_ARCHAEOLOGIST_CHAMPION("Deranged Archaeologist Champion"),
    I("I\"),
    MAGE_OF_THE_SWAMP("Mage of the Swamp"),
    A_SMASHING_TIME("A Smashing Time"),
    GIANT_MOLE_CHAMPION("Giant Mole Champion"),
    AVOIDING_THOSE_LITTLE_ARMS("Avoiding Those Little Arms"),
    KING_BLACK_DRAGON_CHAMPION("King Black Dragon Champion"),
    ANTIFIRE_PROTECTION("Antifire Protection"),
    CLAW_CLIPPER("Claw Clipper"),
    HIDE_PENETRATION("Hide Penetration"),
    MASTER_OF_BROAD_WEAPONRY("Master of Broad Weaponry"),
    BACK_TO_OUR_ROOTS("Back to Our Roots"),
    PERILOUS_NOVICE("Perilous Novice"),
    MOONS_OF_PERIL_SPEED_TRIALIST("Moons of Peril Speed-Trialist"),
    LUNAR_TRIPLET("Lunar Triplet"),
    SIT_BACK_AND_RELAX("Sit Back and Relax"),
    SQUASHING_THE_GIANT("Squashing the Giant"),
    OBOR_CHAMPION("Obor Champion"),
    BACK_TO_THE_WALL("Back to the Wall"),
    ROYAL_TITAN_ADEPT("Royal Titan Adept"),
    IT_TAKES_TOO_LONG("It takes too long"),
    ROYAL_TITAN_CHAMPION("Royal Titan Champion"),
    SARACHNIS_CHAMPION("Sarachnis Champion"),
    NEWSPAPER_ENTHUSIAST("Newspaper Enthusiast"),
    SCURRIUS_CHAMPION("Scurrius Champion"),
    EFFICIENT_PEST_CONTROL("Efficient Pest Control"),
    PERFECT_SCURRIUS("Perfect Scurrius"),
    SHELLBANE_SPEEDRUNNER("Shellbane Speedrunner"),
    SHELLBANE_VETERAN("Shellbane Veteran"),
    PERFECT_SHELLBANE("Perfect Shellbane"),
    A_FROZEN_FOE_FROM_THE_PAST("A Frozen Foe from the Past"),
    DEMONIC_WEAKENING("Demonic Weakening"),
    SKOTIZO_CHAMPION("Skotizo Champion"),
    DEMONBANE_WEAPONRY("Demonbane Weaponry"),
    THE_LONE_ANGLER("The Lone Angler"),
    TEMPOROSS_CHAMPION("Tempoross Champion"),
    YOU("You\"),
    HUEYCOATL_CHAMPION("Hueycoatl Champion"),
    CAN_WE_FIX_IT("Can We Fix It?"),
    WINTERTODT_CHAMPION("Wintertodt Champion"),
    LEAVING_NO_ONE_BEHIND("Leaving No One Behind"),
    THEY_GROW_UP_TOO_FAST("They Grow Up Too Fast"),
    DON("Don\"),
    DON("Don\"),
    ABYSSAL_ADEPT("Abyssal Adept"),
    AMOXLIATL_SPEED_TRIALIST("Amoxliatl Speed-Trialist"),
    AMOXLIATL_ADEPT("Amoxliatl Adept"),
    NAGUA_NEGATION("Nagua Negation"),
    KEMO_MAKTI("Kemo Makti"),
    TOTALLY_SHATTERED("Totally Shattered"),
    JUST_LIKE_THAT("Just Like That"),
    FAITHLESS_CRYPT_RUN("Faithless Crypt Run"),
    SMARTER_THAN_A_COW("Smarter than a Cow"),
    CALLISTO_ADEPT("Callisto Adept"),
    CHAOS_ELEMENTAL_ADEPT("Chaos Elemental Adept"),
    THE_FLINCHER("The Flincher"),
    HOARDER("Hoarder"),
    PRAYING_TO_THE_GODS("Praying to the Gods"),
    CHAOS_FANATIC_ADEPT("Chaos Fanatic Adept"),
    COMMANDER_SHOWDOWN("Commander Showdown"),
    COMMANDER_ZILYANA_ADEPT("Commander Zilyana Adept"),
    CRAZY_ARCHAEOLOGIST_ADEPT("Crazy Archaeologist Adept"),
    DAGANNOTH_PRIME_ADEPT("Dagannoth Prime Adept"),
    DAGANNOTH_REX_ADEPT("Dagannoth Rex Adept"),
    DAGANNOTH_SUPREME_ADEPT("Dagannoth Supreme Adept"),
    GENERAL_GRAARDOR_ADEPT("General Graardor Adept"),
    OURG_FREEZER("Ourg Freezer"),
    GENERAL_SHOWDOWN("General Showdown"),
    WHY_ARE_YOU_RUNNING("Why Are You Running?"),
    WHACK_A_MOLE("Whack-a-Mole"),
    HEAL_NO_MORE("Heal No More"),
    GRANITE_FOOTWORK("Granite Footwork"),
    DON("Don\"),
    STATIC_AWARENESS("Static Awareness"),
    GROTESQUE_GUARDIANS_ADEPT("Grotesque Guardians Adept"),
    PRISON_BREAK("Prison Break"),
    HESPORI_ADEPT("Hespori Adept"),
    HESPORISN("Hesporisn\"),
    WEED_WHACKER("Weed Whacker"),
    DEMONIC_SHOWDOWN("Demonic Showdown"),
    DEMONBANE_WEAPONRY_II("Demonbane Weaponry II"),
    K("K\"),
    YARR_NO_MORE("Yarr No More"),
    KALPHITE_QUEEN_ADEPT("Kalphite Queen Adept"),
    CHITIN_PENETRATOR("Chitin Penetrator"),
    WHO_IS_THE_KING_NOW("Who Is the King Now?"),
    KRAKEN_ADEPT("Kraken Adept"),
    KRAKAN("Krakan\"),
    UNNECESSARY_OPTIMISATION("Unnecessary Optimisation"),
    AIRBORNE_SHOWDOWN("Airborne Showdown"),
    KREE("Kree\"),
    FORTIFIED("Fortified"),
    PERILOUS_DANCER("Perilous Dancer"),
    PERILOUS_CHAMPION("Perilous Champion"),
    THE_CLONE_ZONE("The Clone Zone"),
    MOONS_OF_PERIL_SPEED_CHASER("Moons of Peril Speed-Chaser"),
    FAT_OF_THE_LAND("Fat of the Land"),
    BETRAYAL("Betrayal"),
    PHANTOM_MUSPAH_ADEPT("Phantom Muspah Adept"),
    ROYAL_TITAN_SPEED_RUNNER("Royal Titan Speed-Runner"),
    PERFECT_ROYAL_TITANS("Perfect Royal Titans"),
    TITAN_KILLER("Titan Killer"),
    I_NEED_ROOM("I need room"),
    INSPECT_REPELLENT("Inspect Repellent"),
    READY_TO_POUNCE("Ready to Pounce"),
    I_CAN("I Can\"),
    GUARDIANS_NO_MORE("Guardians No More"),
    SCORPIA_ADEPT("Scorpia Adept"),
    SHELLBANE_SURVIVOR("Shellbane Survivor"),
    FEATHERWEIGHT_FIGHTER("Featherweight Fighter"),
    SKOTIZO_ADEPT("Skotizo Adept"),
    DRESS_LIKE_YOU_MEAN_IT("Dress Like You Mean It"),
    WHY_COOK("Why Cook?"),
    PILLAR_LOVER("Pillar Lover"),
    I("I\"),
    HUEYCOATL_ADEPT("Hueycoatl Adept"),
    NIGHTMARE_ADEPT("Nightmare Adept"),
    THEATRE_OF_BLOOD_SM_ADEPT("Theatre of Blood: SM Adept"),
    NOVICE_TOMB_EXPLORER("Novice Tomb Explorer"),
    CONFIDENT_RAIDER("Confident Raider"),
    MOVIN("Movin\"),
    NOVICE_TOMB_LOOTER("Novice Tomb Looter"),
    VENENATIS_ADEPT("Venenatis Adept"),
    VET("Vet\"),
    WHY_FLETCH("Why Fletch?"),
    ZULRAH_ADEPT("Zulrah Adept"),
    DEMONIC_REBOUND("Demonic Rebound"),
    RESPIRATORY_RUNNER("Respiratory Runner"),
    ABYSSAL_VETERAN("Abyssal Veteran"),
    PERFECT_SIRE("Perfect Sire"),
    ALCHEMICAL_VETERAN("Alchemical Veteran"),
    AMOXLIATL_SPEED_CHASER("Amoxliatl Speed-Chaser"),
    WITHOUT_RALOS("Without Ralos\"),
    ARAXXOR_SPEED_TRIALIST("Araxxor Speed-Trialist"),
    RELAXXOR("Relaxxor"),
    ARAXXOR_VETERAN("Araxxor Veteran"),
    REFLECTING_ON_THIS_ENCOUNTER("Reflecting on This Encounter"),
    BRUTUS_SPEED_TRIALIST("Brutus Speed-Trialist"),
    CALLISTO_VETERAN("Callisto Veteran"),
    CERBERUS_VETERAN("Cerberus Veteran"),
    UNREQUIRED_ANTIFIRE("Unrequired Antifire"),
    GHOST_BUSTER("Ghost Buster"),
    ANTI_BITE_MECHANICS("Anti-Bite Mechanics"),
    SHAYZIEN_SPECIALIST("Shayzien Specialist"),
    PERFECTLY_BALANCED("Perfectly Balanced"),
    MUTTA_DIET("Mutta-diet"),
    TOGETHER_WE("Together We\"),
    CRYO_NO_MORE("Cryo No More"),
    CHAMBERS_OF_XERIC_VETERAN("Chambers of Xeric Veteran"),
    UNDYING_RAID_TEAM("Undying Raid Team"),
    DANCING_WITH_STATUES("Dancing with Statues"),
    REDEMPTION_ENTHUSIAST("Redemption Enthusiast"),
    KILL_IT_WITH_FIRE("Kill It with Fire"),
    BLIZZARD_DODGER("Blizzard Dodger"),
    DUST_SEEKER("Dust Seeker"),
    CHAOS_ELEMENTAL_VETERAN("Chaos Elemental Veteran"),
    COMMANDER_ZILYANA_VETERAN("Commander Zilyana Veteran"),
    REMINISCE("Reminisce"),
    CHICKEN_KILLER("Chicken Killer"),
    HOT_ON_YOUR_FEET("Hot on Your Feet"),
    FINDING_THE_WEAK_SPOT("Finding the Weak Spot"),
    CORPOREAL_BEAST_VETERAN("Corporeal Beast Veteran"),
    CORRUPTED_GAUNTLET_VETERAN("Corrupted Gauntlet Veteran"),
    3_2_1_MAGE("3, 2, 1 - Mage"),
    WOLF_PUNCHER("Wolf Puncher"),
    EGNIOL_DIET("Egniol Diet"),
    GAUNTLET_VETERAN("Gauntlet Veteran"),
    CRYSTALLINE_WARRIOR("Crystalline Warrior"),
    3_2_1_RANGE("3, 2, 1 - Range"),
    FROM_ONE_KING_TO_ANOTHER("From One King to Another"),
    DEATH_TO_THE_SEER_KING("Death to the Seer King"),
    DEATH_TO_THE_WARRIOR_KING("Death to the Warrior King"),
    TOPPLING_THE_DIARCHY("Toppling the Diarchy"),
    RAPID_SUCCESSION("Rapid Succession"),
    DEATH_TO_THE_ARCHER_KING("Death to the Archer King"),
    IF_GORILLAS_COULD_FLY("If Gorillas Could Fly"),
    HITTING_THEM_WHERE_IT_HURTS("Hitting Them Where It Hurts"),
    DOOM_ADEPT("Doom Adept"),
    DOOM_CRAWLER("Doom Crawler"),
    EXPOSED_DOOM("Exposed Doom"),
    DUKE_SUCELLUS_ADEPT("Duke Sucellus Adept"),
    DUKE_SUCELLUS_SPEED_TRIALIST("Duke Sucellus Speed-Trialist"),
    I_WAS_HERE_FIRST("I was here first!"),
    DENIED("Denied"),
    FURBALL("Furball"),
    FRAGMENT_OF_SEREN_SPEED_TRIALIST("Fragment of Seren Speed-Trialist"),
    GALVEK_SPEED_TRIALIST("Galvek Speed-Trialist"),
    GENERAL_GRAARDOR_VETERAN("General Graardor Veteran"),
    OURG_FREEZER_II("Ourg Freezer II"),
    HARD_HITTER("Hard Hitter"),
    GLOUGH_SPEED_TRIALIST("Glough Speed-Trialist"),
    GROTESQUE_GUARDIANS_VETERAN("Grotesque Guardians Veteran"),
    PERFECT_GROTESQUE_GUARDIANS("Perfect Grotesque Guardians"),
    GROTESQUE_GUARDIANS_SPEED_TRIALIST("Grotesque Guardians Speed-Trialist"),
    FROM_DUSK("From Dusk..."),
    DONE_BEFORE_DUSK("Done before Dusk"),
    PLANT_BASED_DIET("Plant-Based Diet"),
    HESPORI_SPEED_TRIALIST("Hespori Speed-Trialist"),
    K("K\"),
    THE_BANE_OF_DEMONS("The Bane of Demons"),
    DEMONIC_DEFENCE("Demonic Defence"),
    PRAYER_SMASHER("Prayer Smasher"),
    KALPHITE_QUEEN_VETERAN("Kalphite Queen Veteran"),
    INSECT_DEFLECTION("Insect Deflection"),
    TEN_TACLES("Ten-tacles"),
    KREE("Kree\"),
    LEVIATHAN_SPEED_TRIALIST("Leviathan Speed-Trialist"),
    LEVIATHAN_ADEPT("Leviathan Adept"),
    HIGH_HITTER("High Hitter"),
    NEX_SURVIVORS("Nex Survivors"),
    NEX_VETERAN("Nex Veteran"),
    PHANTOM_MUSPAH_VETERAN("Phantom Muspah Veteran"),
    VERSATILE_DRAINER("Versatile Drainer"),
    PHANTOM_MUSPAH_SPEED_TRIALIST("Phantom Muspah Speed-Trialist"),
    CAN("Can\"),
    PHOSANI("Phosani\"),
    NO_TIME_TO_PRAY("No time to pray"),
    SCORPIA_VETERAN("Scorpia Veteran"),
    DEMON_EVASION("Demon Evasion"),
    UP_FOR_THE_CHALLENGE("Up for the Challenge"),
    HUEYCOATL_VETERAN("Hueycoatl Veteran"),
    PERFECT_HUEYCOATL("Perfect Hueycoatl"),
    HUEYCOATL_SPEED_TRIALIST("Hueycoatl Speed-Trialist"),
    MIMIC_VETERAN("Mimic Veteran"),
    NIGHTMARE_5_SCALE_SPEED_TRIALIST("Nightmare (5-Scale) Speed-Trialist"),
    NIGHTMARE_SOLO_SPEED_TRIALIST("Nightmare (Solo) Speed-Trialist"),
    SLEEP_TIGHT("Sleep Tight"),
    EXPLOSION("Explosion!"),
    NIGHTMARE_VETERAN("Nightmare Veteran"),
    THEATRE_OF_BLOOD_VETERAN("Theatre of Blood Veteran"),
    DON("Don\"),
    NO_PILLAR("No-Pillar"),
    JUST_TO_BE_SAFE("Just To Be Safe"),
    ANTICOAGULANTS("Anticoagulants"),
    THEY_WON("They Won\"),
    NYLOCAS_ON_THE_ROCKS("Nylocas, On the Rocks"),
    APPROPRIATE_TOOLS("Appropriate Tools"),
    PASS_IT_ON("Pass It On"),
    ATTACK_STEP_WAIT("Attack, Step, Wait"),
    CHALLY_TIME("Chally Time"),
    SPEC("Spec\"),
    HAZARD_PREVENTION("Hazard Prevention"),
    THERMONUCLEAR_VETERAN("Thermonuclear Veteran"),
    I("I\"),
    PERFECT_APMEKEN("Perfect Apmeken"),
    HARDCORE_TOMBS("Hardcore Tombs"),
    DOWN_DO_SPECS("Down Do Specs"),
    PERFECT_HET("Perfect Het"),
    PERFECT_CRONDIS("Perfect Crondis"),
    NO_SKIPPING_ALLOWED("No skipping allowed"),
    HELPFUL_SPIRIT_WHO("Helpful spirit who?"),
    DROPPED_THE_BALL("Dropped the ball"),
    TOMB_EXPLORER("Tomb Explorer"),
    HARDCORE_RAIDERS("Hardcore Raiders"),
    NOVICE_TOMB_RAIDER("Novice Tomb Raider"),
    EXPERT_TOMB_EXPLORER("Expert Tomb Explorer"),
    RAPID_RELOAD("Rapid Reload"),
    UNENDING_TORMENT("Unending Torment"),
    TWO_TIMES_THE_TORMENT("Two Times the Torment"),
    THROUGH_FIRE_AND_FLAMES("Through Fire and Flames"),
    FACING_JAD_HEAD_ON_III("Facing Jad Head-on III"),
    THE_II_JAD_CHALLENGE("The II Jad Challenge"),
    TZHAAR_KET_RAK("TzHaar-Ket-Rak\"),
    HALF_WAY_THERE("Half-Way There"),
    A_NEAR_MISS("A Near Miss!"),
    FIGHT_CAVES_VETERAN("Fight Caves Veteran"),
    FACING_JAD_HEAD_ON("Facing Jad Head-on"),
    VARDORVIS_ADEPT("Vardorvis Adept"),
    VARDORVIS_SPEED_TRIALIST("Vardorvis Speed-Trialist"),
    VENENATIS_VETERAN("Venenatis Veteran"),
    VET("Vet\"),
    STICK("Stick \"),
    ZOMBIE_DESTROYER("Zombie Destroyer"),
    VORKATH_VETERAN("Vorkath Veteran"),
    WHISPERER_SPEED_TRIALIST("Whisperer Speed-Trialist"),
    WHISPERER_ADEPT("Whisperer Adept"),
    TENTACULAR("Tentacular"),
    BACK_SO_SOON("Back so soon?"),
    YAMA_SPEED_TRIALIST("Yama Speed-Trialist"),
    YAMA_ADEPT("Yama Adept"),
    TEAM_PLAYER("Team Player"),
    ZALCANO_VETERAN("Zalcano Veteran"),
    PERFECT_ZALCANO("Perfect Zalcano"),
    THE_SPURNED_HERO("The Spurned Hero"),
    ZULRAH_SPEED_TRIALIST("Zulrah Speed-Trialist"),
    SNAKE_REBOUND("Snake Rebound"),
    SNAKE_SNAKE_SNAAAAAAKE("Snake. Snake!? Snaaaaaake!"),
    ZULRAH_VETERAN("Zulrah Veteran"),
    THE_FLAME_SKIPPER("The Flame Skipper"),
    ALCHEMICAL_MASTER("Alchemical Master"),
    ALCHEMICAL_SPEED_CHASER("Alchemical Speed-Chaser"),
    DON("Don\"),
    WORKING_OVERTIME("Working Overtime"),
    UNREQUIRED_ANTIPOISONS("Unrequired Antipoisons"),
    LIGHTNING_LURE("Lightning Lure"),
    ALCLEANICAL_HYDRA("Alcleanical Hydra"),
    MIXING_CORRECTLY("Mixing Correctly"),
    ARAXXOR_SPEED_CHASER("Araxxor Speed-Chaser"),
    PERFECT_ARAXXOR("Perfect Araxxor"),
    ARAXXOR_MASTER("Araxxor Master"),
    ARACHNID_LOVER("Arachnid Lover"),
    ARAXYTE_BETRAYAL("Araxyte Betrayal"),
    LET_IT_SEEP_IN("Let it seep in"),
    AROOO_NO_MORE("Arooo No More"),
    CERBERUS_MASTER("Cerberus Master"),
    CHAMBERS_OF_XERIC_5_SCALE_SPEED_CHASER("Chambers of Xeric (5-Scale) Speed-Chaser"),
    CHAMBERS_OF_XERIC_TRIO_SPEED_CHASER("Chambers of Xeric (Trio) Speed-Chaser"),
    CHAMBERS_OF_XERIC_SOLO_SPEED_CHASER("Chambers of Xeric (Solo) Speed-Chaser"),
    PLAYING_WITH_LASERS("Playing with Lasers"),
    ANVIL_NO_MORE("Anvil No More"),
    PERFECT_OLM_SOLO("Perfect Olm (Solo)"),
    BLIND_SPOT("Blind Spot"),
    A_NOT_SO_SPECIAL_LIZARD("A Not So Special Lizard"),
    PUTTING_IT_OLM_ON_THE_LINE("Putting It Olm on the Line"),
    CHAMBERS_OF_XERIC_MASTER("Chambers of Xeric Master"),
    UNDYING_RAIDER("Undying Raider"),
    NO_TIME_FOR_DEATH("No Time for Death"),
    PERFECT_OLM_TRIO("Perfect Olm (Trio)"),
    STOP_DROP_AND_ROLL("Stop Drop and Roll"),
    IMMORTAL_RAIDER("Immortal Raider"),
    CHAMBERS_OF_XERIC_CM_MASTER("Chambers of Xeric: CM Master"),
    IMMORTAL_RAID_TEAM("Immortal Raid Team"),
    CHAMBERS_OF_XERIC_CM_5_SCALE_SPEED_CHASER("Chambers of Xeric: CM (5-Scale) Speed-Chaser"),
    CHAMBERS_OF_XERIC_CM_TRIO_SPEED_CHASER("Chambers of Xeric: CM (Trio) Speed-Chaser"),
    CHAMBERS_OF_XERIC_CM_SOLO_SPEED_CHASER("Chambers of Xeric: CM (Solo) Speed-Chaser"),
    MOVING_COLLATERAL("Moving Collateral"),
    CORPOREAL_BEAST_MASTER("Corporeal Beast Master"),
    CORRUPTED_WARRIOR("Corrupted Warrior"),
    CORRUPTED_GAUNTLET_MASTER("Corrupted Gauntlet Master"),
    CORRUPTED_GAUNTLET_SPEED_CHASER("Corrupted Gauntlet Speed-Chaser"),
    PERFECT_CORRUPTED_HUNLLEF("Perfect Corrupted Hunllef"),
    DEFENCE_DOESN("Defence Doesn\"),
    DEFENCE_DOESN("Defence Doesn\"),
    GAUNTLET_SPEED_CHASER("Gauntlet Speed-Chaser"),
    GAUNTLET_MASTER("Gauntlet Master"),
    PERFECT_CRYSTALLINE_HUNLLEF("Perfect Crystalline Hunllef"),
    DOOM_CHASER("Doom Chaser"),
    MOKHAIOTL_DRIFT("Mokhaiotl Drift"),
    MINE("Mine\"),
    DOOM_VETERAN("Doom Veteran"),
    GRUB_PATROL("Grub Patrol"),
    COLD_FEET("Cold Feet"),
    DUKE_SUCELLUS_SPEED_CHASER("Duke Sucellus Speed-Chaser"),
    PERFECT_DUKE_SUCELLUS("Perfect Duke Sucellus"),
    DUKE_SUCELLUS_MASTER("Duke Sucellus Master"),
    COLOSSEUM_SPEED_CHASER("Colosseum Speed-Chaser"),
    I_BROUGHT_MINE_TOO("I Brought Mine Too"),
    SPORTSMANSHIP("Sportsmanship"),
    SHOWBOATING("Showboating"),
    ONE_OFF("One-off"),
    ("... \"),
    PERFECT_GROTESQUE_GUARDIANS_II("Perfect Grotesque Guardians II"),
    GROTESQUE_GUARDIANS_SPEED_CHASER("Grotesque Guardians Speed-Chaser"),
    HESPORI_SPEED_CHASER("Hespori Speed-Chaser"),
    ONE_HUNDRED_TENTACLES("One Hundred Tentacles"),
    COLLATERAL_DAMAGE("Collateral Damage"),
    SWOOP_NO_MORE("Swoop No More"),
    LEVIATHAN_MASTER("Leviathan Master"),
    LEVIATHAN_SPEED_CHASER("Leviathan Speed-Chaser"),
    SERPENTINE_SOLO("Serpentine Solo"),
    PERFECT_LEVIATHAN("Perfect Leviathan"),
    NEX_TRIO("Nex Trio"),
    CONTAIN_THIS("Contain this!"),
    THERE_IS_NO_ESCAPE("There is no escape!"),
    NEX_MASTER("Nex Master"),
    SHADOWS_MOVE("Shadows Move..."),
    A_SIPHON_WILL_SOLVE_THIS("A siphon will solve this"),
    WALK_STRAIGHT_PRAY_TRUE("Walk Straight Pray True"),
    MORE_THAN_JUST_A_RANGED_WEAPON("More than just a ranged weapon"),
    SPACE_IS_TIGHT("Space is Tight"),
    PHANTOM_MUSPAH_SPEED_CHASER("Phantom Muspah Speed-Chaser"),
    ESSENCE_FARMER("Essence Farmer"),
    PHANTOM_MUSPAH_MASTER("Phantom Muspah Master"),
    CRUSH_HOUR("Crush Hour"),
    I_WOULD_SIMPLY_REACT("I Would Simply React"),
    DREAMLAND_EXPRESS("Dreamland Express"),
    PHOSANI("Phosani\"),
    PHOSANI("Phosani\"),
    PRECISE_POSITIONING("Precise Positioning"),
    IS_IT_A_BIRD("Is it a bird?"),
    HUEYCOATL_SPEED_CHASER("Hueycoatl Speed-Chaser"),
    NIGHTMARE_MASTER("Nightmare Master"),
    NIGHTMARE_5_SCALE_SPEED_CHASER("Nightmare (5-Scale) Speed-Chaser"),
    NIGHTMARE_SOLO_SPEED_CHASER("Nightmare (Solo) Speed-Chaser"),
    PERFECT_NIGHTMARE("Perfect Nightmare"),
    PERFECT_XARPUS("Perfect Xarpus"),
    PERFECT_VERZIK("Perfect Verzik"),
    POP_IT("Pop It"),
    PERFECT_SOTETSEG("Perfect Sotetseg"),
    PERFECT_MAIDEN("Perfect Maiden"),
    THEATRE_OF_BLOOD_MASTER("Theatre of Blood Master"),
    BACK_IN_MY_DAY("Back in My Day..."),
    THEATRE_TRIO_SPEED_CHASER("Theatre (Trio) Speed-Chaser"),
    TWO_DOWN("Two-Down"),
    PERFECT_BLOAT("Perfect Bloat"),
    CAN_YOU_DANCE("Can You Dance?"),
    THEATRE_4_SCALE_SPEED_CHASER("Theatre (4-Scale) Speed-Chaser"),
    THEATRE_5_SCALE_SPEED_CHASER("Theatre (5-Scale) Speed-Chaser"),
    PERFECT_NYLOCAS("Perfect Nylocas"),
    A_TIMELY_SNACK("A Timely Snack"),
    CAN("Can\"),
    THEATRE_OF_BLOOD_SM_SPEED_CHASER("Theatre of Blood: SM Speed-Chaser"),
    HARD_MODE_COMPLETED_IT("Hard Mode? Completed It"),
    PERFECT_WARDENS("Perfect Wardens"),
    TOMB_RAIDER("Tomb Raider"),
    YOU_ARE_NOT_PREPARED("You are not prepared"),
    TOMB_LOOTER("Tomb Looter"),
    PERFECT_SCABARAS("Perfect Scabaras"),
    PERFECT_KEPHRI("Perfect Kephri"),
    BETTER_GET_MOVIN("Better get movin\"),
    PERFECT_ZEBAK("Perfect Zebak"),
    PERFECT_AKKHA("Perfect Akkha"),
    PERFECT_BA_BA("Perfect Ba-Ba"),
    CHOMPINGTON("Chompington"),
    TOMBS_SPEED_RUNNER("Tombs Speed Runner"),
    SOMETHING_OF_AN_EXPERT_MYSELF("Something of an expert myself"),
    EXPERT_TOMB_LOOTER("Expert Tomb Looter"),
    RESOURCEFUL_RAIDER("Resourceful Raider"),
    BA_BANANZA("Ba-Bananza"),
    BUT_DAMAGE("But... Damage"),
    DOESN("Doesn\"),
    ROCKIN("Rockin\"),
    ALL_OUT_OF_MEDICS("All out of medics"),
    WARDEN("Warden\"),
    FANCY_FEET("Fancy feet"),
    THREE_TIMES_THE_THRASHING("Three Times the Thrashing"),
    FACING_JAD_HEAD_ON_IV("Facing Jad Head-on IV"),
    THE_IV_JAD_CHALLENGE("The IV Jad Challenge"),
    SUPPLIES_WHO_NEEDS("Supplies? Who Needs \"),
    TZHAAR_KET_RAK("TzHaar-Ket-Rak\"),
    MULTI_STYLE_SPECIALIST("Multi-Style Specialist"),
    NIBBLERS_BEGONE("Nibblers, Begone!"),
    DENYING_THE_HEALERS("Denying the Healers"),
    FIGHT_CAVES_MASTER("Fight Caves Master"),
    YOU_DIDN("You Didn\"),
    FIGHT_CAVES_SPEED_CHASER("Fight Caves Speed-Chaser"),
    PERFECT_VARDORVIS("Perfect Vardorvis"),
    BUDGET_CUTTER("Budget Cutter"),
    VARDORVIS_MASTER("Vardorvis Master"),
    VARDORVIS_SPEED_CHASER("Vardorvis Speed-Chaser"),
    VORKATH_SPEED_CHASER("Vorkath Speed-Chaser"),
    DODGING_THE_DRAGON("Dodging the Dragon"),
    VORKATH_MASTER("Vorkath Master"),
    EXTENDED_ENCOUNTER("Extended Encounter"),
    THE_WALK("The Walk"),
    WHISPERER_SPEED_CHASER("Whisperer Speed-Chaser"),
    WHISPERER_MASTER("Whisperer Master"),
    PERFECT_WHISPERER("Perfect Whisperer"),
    NO_TOPPINGS_NO_DRINKS_THANKS("No toppings, no drinks, thanks"),
    YAMA_VETERAN("Yama Veteran"),
    FIRE_FIGHTER("Fire fighter"),
    YAMA_SPEED_CHASER("Yama Speed-Chaser"),
    SHADOW_DANCER("Shadow dancer"),
    ZULRAH_SPEED_CHASER("Zulrah Speed-Chaser"),
    PERFECT_ZULRAH("Perfect Zulrah"),
    ZULRAH_MASTER("Zulrah Master"),
    NO_PRESSURE("No Pressure"),
    ALCHEMICAL_SPEED_RUNNER("Alchemical Speed-Runner"),
    PERFECT_ARAXXOR_2("Perfect Araxxor 2"),
    SWIMMING_IN_VENOM("Swimming in Venom"),
    ARAXXOR_SPEED_RUNNER("Araxxor Speed-Runner"),
    CHAMBERS_OF_XERIC_SOLO_SPEED_RUNNER("Chambers of Xeric (Solo) Speed-Runner"),
    CHAMBERS_OF_XERIC_GRANDMASTER("Chambers of Xeric Grandmaster"),
    CHAMBERS_OF_XERIC_5_SCALE_SPEED_RUNNER("Chambers of Xeric (5-Scale) Speed-Runner"),
    CHAMBERS_OF_XERIC_TRIO_SPEED_RUNNER("Chambers of Xeric (Trio) Speed-Runner"),
    CHAMBERS_OF_XERIC_CM_SOLO_SPEED_RUNNER("Chambers of Xeric: CM (Solo) Speed-Runner"),
    CHAMBERS_OF_XERIC_CM_GRANDMASTER("Chambers of Xeric: CM Grandmaster"),
    CHAMBERS_OF_XERIC_CM_5_SCALE_SPEED_RUNNER("Chambers of Xeric: CM (5-Scale) Speed-Runner"),
    CHAMBERS_OF_XERIC_CM_TRIO_SPEED_RUNNER("Chambers of Xeric: CM (Trio) Speed-Runner"),
    ANIMAL_WHISPERER("Animal Whisperer"),
    PEACH_CONJURER("Peach Conjurer"),
    EGNIOL_DIET_II("Egniol Diet II"),
    CORRUPTED_GAUNTLET_SPEED_RUNNER("Corrupted Gauntlet Speed-Runner"),
    WOLF_PUNCHER_II("Wolf Puncher II"),
    CORRUPTED_GAUNTLET_GRANDMASTER("Corrupted Gauntlet Grandmaster"),
    GAUNTLET_SPEED_RUNNER("Gauntlet Speed-Runner"),
    MOPPING_UP("Mopping up"),
    DUEL_OF_MOKHAIOTL("Duel of Mokhaiotl"),
    DARKNESS_IS_YOUR_ALLY("Darkness Is Your Ally?"),
    DOOM_RACER("Doom Racer"),
    IT("It\"),
    THE_PRAYING_MANTIS("The Praying Mantis"),
    PERFECT_DOOM("Perfect Doom"),
    DUKE_SUCELLUS_SPEED_RUNNER("Duke Sucellus Speed-Runner"),
    DUKE_SUCELLUS_SLEEPER("Duke Sucellus Sleeper"),
    MIRROR_IMAGE("Mirror Image"),
    REINFORCEMENTS("Reinforcements"),
    COLOSSEUM_SPEED_RUNNER("Colosseum Speed-Runner"),
    SLOW_DANCING_IN_THE_SAND("Slow Dancing in the Sand"),
    PERFECT_FOOTWORK("Perfect Footwork"),
    COLOSSEUM_GRAND_CHAMPION("Colosseum Grand Champion"),
    OURG_KILLER("Ourg Killer"),
    KEEP_AWAY("Keep Away"),
    DEFENCE_MATTERS("Defence Matters"),
    GROTESQUE_GUARDIANS_SPEED_RUNNER("Grotesque Guardians Speed-Runner"),
    DEMON_WHISPERER("Demon Whisperer"),
    ASH_COLLECTOR("Ash Collector"),
    THE_WORST_RANGED_WEAPON("The Worst Ranged Weapon"),
    FEATHER_HUNTER("Feather Hunter"),
    LEVIATHAN_SPEED_RUNNER("Leviathan Speed-Runner"),
    UNCONVENTIONAL("Unconventional"),
    LEVIATHAN_SLEEPER("Leviathan Sleeper"),
    I_SHOULD_SEE_A_DOCTOR("I should see a doctor"),
    NEX_DUO("Nex Duo"),
    PERFECT_NEX("Perfect Nex"),
    PHANTOM_MUSPAH_MANIPULATOR("Phantom Muspah Manipulator"),
    PHANTOM_MUSPAH_SPEED_RUNNER("Phantom Muspah Speed-Runner"),
    CAN("Can\"),
    PHOSANI("Phosani\"),
    PERFECT_PHOSANI("Perfect Phosani\"),
    PHOSANI("Phosani\"),
    HUEYCOATL_SPEED_RUNNER("Hueycoatl Speed-Runner"),
    TERRIBLE_PARENT("Terrible Parent"),
    NIGHTMARE_SOLO_SPEED_RUNNER("Nightmare (Solo) Speed-Runner"),
    A_LONG_TRIP("A Long Trip"),
    NIGHTMARE_5_SCALE_SPEED_RUNNER("Nightmare (5-Scale) Speed-Runner"),
    THEATRE_OF_BLOOD_GRANDMASTER("Theatre of Blood Grandmaster"),
    THEATRE_5_SCALE_SPEED_RUNNER("Theatre (5-Scale) Speed-Runner"),
    THEATRE_4_SCALE_SPEED_RUNNER("Theatre (4-Scale) Speed-Runner"),
    THEATRE_TRIO_SPEED_RUNNER("Theatre (Trio) Speed-Runner"),
    THEATRE_DUO_SPEED_RUNNER("Theatre (Duo) Speed-Runner"),
    MORYTANIA_ONLY("Morytania Only"),
    PERFECT_THEATRE("Perfect Theatre"),
    THEATRE_HM_5_SCALE_SPEED_RUNNER("Theatre: HM (5-Scale) Speed-Runner"),
    STOP_RIGHT_THERE("Stop Right There!"),
    PERSONAL_SPACE("Personal Space"),
    HARDER_MODE_I("Harder Mode I"),
    ROYAL_AFFAIRS("Royal Affairs"),
    THEATRE_HM_4_SCALE_SPEED_RUNNER("Theatre: HM (4-Scale) Speed-Runner"),
    TEAM_WORK_MAKES_THE_DREAM_WORK("Team Work Makes the Dream Work"),
    THEATRE_HM_TRIO_SPEED_RUNNER("Theatre: HM (Trio) Speed-Runner"),
    PACK_LIKE_A_YAK("Pack Like a Yak"),
    HARDER_MODE_II("Harder Mode II"),
    THEATRE_OF_BLOOD_HM_GRANDMASTER("Theatre of Blood: HM Grandmaster"),
    HARDER_MODE_III("Harder Mode III"),
    NYLO_SNIPER("Nylo Sniper"),
    INSANITY("Insanity"),
    PERFECTION_OF_APMEKEN("Perfection of Apmeken"),
    PERFECTION_OF_HET("Perfection of Het"),
    ALL_PRAISE_ZEBAK("All Praise Zebak"),
    AKKHAN("Akkhan\"),
    TOMBS_SPEED_RUNNER_III("Tombs Speed Runner III"),
    TOMBS_SPEED_RUNNER_II("Tombs Speed Runner II"),
    PERFECTION_OF_CRONDIS("Perfection of Crondis"),
    AMASCUT("Amascut\"),
    EXPERT_TOMB_RAIDER("Expert Tomb Raider"),
    MAYBE_I("Maybe I\"),
    PERFECTION_OF_SCABARAS("Perfection of Scabaras"),
    TZHAAR_KET_RAK("TzHaar-Ket-Rak\"),
    THE_VI_JAD_CHALLENGE("The VI Jad Challenge"),
    IT_WASN("It Wasn\"),
    INFERNO_SPEED_RUNNER("Inferno Speed-Runner"),
    JAD_WHAT_ARE_YOU_DOING_HERE("Jad? What Are You Doing Here?"),
    THE_FLOOR_IS_LAVA("The Floor Is Lava"),
    BUDGET_SETUP("Budget Setup"),
    INFERNO_GRANDMASTER("Inferno Grandmaster"),
    NIBBLER_CHASER("Nibbler Chaser"),
    NO_LUCK_REQUIRED("No Luck Required"),
    PLAYING_WITH_JADS("Playing with Jads"),
    FACING_JAD_HEAD_ON_II("Facing Jad Head-on II"),
    WASN("Wasn\"),
    DENYING_THE_HEALERS_II("Denying the Healers II"),
    FIGHT_CAVES_SPEED_RUNNER("Fight Caves Speed-Runner"),
    NO_TIME_FOR_A_DRINK("No Time for a Drink"),
    AXE_ENTHUSIAST("Axe Enthusiast"),
    VARDORVIS_SLEEPER("Vardorvis Sleeper"),
    VARDORVIS_SPEED_RUNNER("Vardorvis Speed-Runner"),
    FAITHLESS_ENCOUNTER("Faithless Encounter"),
    VORKATH_SPEED_RUNNER("Vorkath Speed-Runner"),
    THE_FREMENNIK_WAY("The Fremennik Way"),
    WHISPERED("Whispered"),
    DARK_MEMORIES("Dark Memories"),
    WHISPERER_SPEED_RUNNER("Whisperer Speed-Runner"),
    CONTRACTUALLY_UNBOUND("Contractually Unbound"),
    YAMA_SPEED_RUNNER("Yama Speed-Runner"),
    CONTRACT_CHOREOGRAPHER("Contract Choreographer"),
    ZULRAH_SPEED_RUNNER("Zulrah Speed-Runner");

    private final String taskName;

    CombatAchievement(String taskName)
    {
        this.taskName = taskName;
    }

    public String getTaskName()
    {
        return taskName;
    }

    /**
     * Returns true if this task is completed for the given client.
     * CA tasks are stored as bits within VarPlayers 2616-2635.
     */
    public boolean isCompleted(net.runelite.api.Client client)
    {
        int index = this.ordinal();
        int varpId = 2616 + (index / 32);
        int bit = index % 32;
        return ((client.getVarpValue(varpId) >> bit) & 1) == 1;
    }
}
